name: CI
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm

      # Get projects set up
      - run: pnpm install
      - run: pnpm bootstrap
      - run: pnpm build

      # Run tests against both Svelte versions using workspace
      - run: pnpm test:workspace
        env:
          CI: true

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm

      # Get projects set up
      - run: pnpm install
      - run: pnpm lint
